name: Package app

on:
  push:
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  workflow_dispatch: ~

jobs:
  push_to_registries:
    name: Push Docker image to GCR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push the containers
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/rosenbergm/martinovykavarny.cz:latest